### ISSUE TITLE
Deprecate cluster-driver-registrar

### ISSUE THREAD

**Issue by jsafrane** [kubernetes-csi/cluster-driver-registrar#48]
Our documentation says:

> As of Kubernetes 1.14, this side car container is being refactored.

It has been two releases without any progress in the refactoring / redesign. The documentation also says that CSIDriver instances should be created "by installation manifest".

In addition, the last released cluster-driver-registrar does not support current v1beta1 CSIDriver, it still uses the v1alpha1 one based on CRD. Kubernetes e2e tests use image tagged as "tmp-test-1.14", which was never officially released.

I think it's time to officially declare that cluster-driver-registrar is deprecated.

Code-wise, these things need to be updated:

- Kubernetes e2e tests must create CSIDriver without the registrar.
- Update kubernetes-csi/docs: https://github.com/kubernetes-csi/docs/pull/183
- Update README here: https://github.com/kubernetes-csi/cluster-driver-registrar/pull/49
- Close all issues / PRs in this repo.

**Comment by msau42** [comment]
+1, there is not much in CSIDriver right now that really needs to be determined dynamically by the plugin.

If we start storing all the plugin capabilities or something like that then maybe this would be useful, but until we have such a need, I think we should reduce our scope.

**Comment by kfox1111** [comment]
+1

**Comment by jsafrane** [comment]
I started updating the docs and other components.

**Comment by msau42** [comment]
All docs have been updated and e2es no longer use it. I'll mark the repo as deprecated in the description
/close
